export const siteConfig = {
  name: "Santos Home Services LLC",
  founder: "Claudinei Santos",
  license: "HIC.0705313",
  licenseState: "Connecticut",
  licenseType: "Home Improvement Contractor",
  domain: "https://santoshomeservicesllc.com",
  phone: "(475) 251-6504",
  phoneRaw: "+14752516504",
  email: "Santoshomeservices2026@gmail.com",
  address: {
    street: "95 Main St Apt 2B",
    city: "Danbury",
    state: "CT",
    zip: "06810",
    country: "US",
  },
  geo: {
    latitude: 41.3948,
    longitude: -73.454,
  },
  hours: "Mo-Sa 07:00-19:00",
  hoursHuman: "Monday – Saturday: 7:00 AM – 7:00 PM | Sunday: Closed",
  serviceAreas: [
    "Danbury",
    "Bethel",
    "Brookfield",
    "New Fairfield",
    "Ridgefield",
    "Newtown",
    "Wilton",
    "Redding",
    "Norwalk",
    "Stamford",
    "Fairfield County",
  ],
  buildZoomScore: 91,
  buildZoomRank: "Top 37% of 93,424 licensed contractors in Connecticut",
};
